---
- name: update configuration
  template:
    src: "../{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - etc/openvpn/ca.crt
    - etc/openvpn/dh.pem
    - etc/openvpn/server.conf
    - etc/openvpn/server.crt

- name: update configuration (restricted permissions)
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: 0600
  with_items:
    - etc/openvpn/server.key
