---
- name: install software | apt
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - libssl-dev
    - liblzo2-dev
    - libpam0g-dev

- name: download source code
  shell: "cd {{ openvpn_compile_from_source_working_directory }} && wget {{ openvpn_compile_from_remote_local }} --output-document={{ openvpn_compile_from_source_local_destination_compressed }}"

- name: uncompress source code
  unarchive:
    src: "{{ openvpn_compile_from_source_local_destination_compressed }}"
    dest: "{{ openvpn_compile_from_source_local_destination }}"

- name: configure and make
  shell: "cd {{ openvpn_compile_from_source_local_destination }} && ./configure && make && sudo make install"
