---
- name: install software | apt
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - openvpn
    - easy-rsa
  when: not openvpn_compile_from_source

- include: compile_from_source.yml
  when: openvpn_compile_from_source
