---
- name: install software | apt
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - openvpn
    - easy-rsa

- name: forward client traffic to internet
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: update confs
  template:
    src: "templates{{ item }}"
    dest: "{{ item }}"
  with_items:
    - /etc/openvpn/server.conf
    - /etc/sysctl.conf

- name: ufw allow ssh
  ufw:
    rule: allow
    name: OpenSSH

- name: ufw allow OpenVPN
  ufw:
    rule: allow
    port: 1194
    proto: udp

- name: update confs
  template:
    src: "templates{{ item }}"
    dest: "{{ item }}"
  with_items:
    - /etc/default/ufw
    - /etc/ufw/before.rules

- name: enable ufw
  sudo_user: root
  ufw:
    state: enabled