---
- name: forward client traffic to internet
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: update confs
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - etc/openvpn/ca.crt
    - etc/openvpn/dh.pem
    - etc/openvpn/server.conf
    - etc/openvpn/server.crt
    - etc/sysctl.conf

- name: update confs (restricted permissions)
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: 0600
  with_items:
    - etc/openvpn/ipp.txt
    - etc/openvpn/server.key

- name: bridge vpn to local ethernet
  sudo_user: root
  shell: iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o TUN0 -j MASQUERADE

- name: start openvpn on boot
  cron:
    name: "start openvpn on boot"
    special_time: reboot
    job: "cd /etc/openvpn && openvpn server.conf >> /tmp/openvpn.log"

- name: include firewall
  include: firewall.yml
  when: openvpn_server_firewall_enabled
