---
- name: ufw allow ssh
  ufw:
    rule: allow
    name: OpenSSH
  when: openvpn_server_firewall_allow_ssh

- name: ufw allow dns lookups
  ufw:
    rule: allow
    from_ip: "{{ openvpn_server_firewall_dns_gateway }}"
    from_port: 53
    name: DNS
  when: openvpn_server_firewall_allow_dns

- name: ufw allow OpenVPN
  ufw:
    rule: allow
    port: 1194
    proto: udp

- name: update confs
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - etc/default/ufw
    - etc/ufw/before.rules

- name: enable ufw
  sudo_user: root
  ufw:
    state: enabled
